# 端口
server:
  port: 8080

# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/procurement?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#日志相关
logging:
  file:
    path: E:\\IdeaProject\\procurementProject\\log\\0418
  level:
    com:
      hs: debug

#扫描mapper层
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml0